# Generated by Django 5.2.7 on 2025-10-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('material_type', models.CharField(choices=[('FILM', 'Plastic Film'), ('INK', 'Ink'), ('SOLVENT', 'Solvent'), ('ADHESIVE', 'Adhesive'), ('HARDENER', 'Hardener')], max_length=20)),
                ('density', models.FloatField(help_text='Density in g/cm³')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('EXTRUSION', 'Extrusion'), ('PRINTING', 'Printing'), ('LAMINATION', 'Lamination'), ('SLITTING', 'Slitting'), ('BAG_MAKING', 'Bag Making')], max_length=20)),
                ('calculation_type', models.CharField(max_length=100)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calculation Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DensityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(help_text='Mass in grams')),
                ('volume', models.FloatField(help_text='Volume in cm³')),
                ('calculated_density', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
        ),
    ]
