# Generated by Django 5.2.7 on 2025-10-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InkFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ink_type', models.CharField(choices=[('PRIMARY', 'Primary (CMYK)'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary'), ('SPOT', 'Spot Color')], max_length=20)),
                ('base_color', models.CharField(blank=True, max_length=50)),
                ('pigment_percentage', models.FloatField(default=0.0)),
                ('binder_percentage', models.FloatField(default=0.0)),
                ('additives_percentage', models.FloatField(default=0.0)),
                ('solvent_percentage', models.FloatField(default=0.0)),
                ('density_g_cm3', models.FloatField(default=1.0)),
                ('coverage_gsm', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('FILM_MASS_LENGTH', 'Film Mass & Length'), ('INK_MASS', 'Ink Mass Needed'), ('MACHINE_SPEED', 'Machine Speed'), ('GSM_CALCULATION', 'GSM Calculation'), ('INK_MIXING', 'Ink Mixing'), ('PRODUCTION_TIME', 'Production Time')], max_length=20)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
