# Generated by Django 5.2.7 on 2025-10-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaminationCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(max_length=50)),
                ('adhesive_type', models.CharField(choices=[('SOLVENTLESS', 'Solventless'), ('SOLVENT_BASE', 'Solvent Base')], max_length=20)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LaminationLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField()),
                ('thickness_unit', models.CharField(default='micron', max_length=10)),
                ('layer_order', models.IntegerField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='lamination.laminationcalculation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
            ],
            options={
                'ordering': ['layer_order'],
            },
        ),
    ]
