# Generated by Django 5.2.7 on 2025-10-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BagMakingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('PIECES_WEIGHT', 'Pieces ↔ Weight'), ('PACKET_WEIGHT', 'Packet Weight'), ('BUNDLE_WEIGHT', 'Bundle/Bale Weight'), ('PRODUCTION_TIME', 'Production Time'), ('YIELD_EFFICIENCY', 'Yield & Efficiency')], max_length=20)),
                ('bag_type', models.CharField(choices=[('FLAT_SHEET', 'Flat Sheet Bag'), ('TUBULAR', 'Tubular Bag'), ('GUSSETED', 'Gusseted Bag'), ('LAMINATED_FLAT', 'Laminated Flat Bag'), ('LAMINATED_TUBULAR', 'Laminated Tubular Bag'), ('LAMINATED_GUSSETED', 'Laminated Gusseted Bag')], max_length=20)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BagLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField()),
                ('thickness_unit', models.CharField(default='micron', max_length=10)),
                ('layer_order', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='bag_making.bagmakingcalculation')),
            ],
            options={
                'ordering': ['layer_order'],
            },
        ),
    ]
