# Generated by Django 5.2.7 on 2025-10-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaminatedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layers', models.JSONField()),
                ('total_thickness_microns', models.FloatField()),
                ('composite_density', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
        migrations.AlterField(
            model_name='salescalculation',
            name='calculation_type',
            field=models.CharField(choices=[('MATERIAL_COST_KG', 'Material Cost per kg'), ('MATERIAL_COST_METER', 'Material Cost per meter'), ('MATERIAL_COST_PIECE', 'Material Cost per piece'), ('COST_PER_ROLL', 'Cost per Roll'), ('ROLL_WEIGHT_FROM_COST', 'Roll Weight from Cost'), ('ORDER_QUANTITY', 'Order Quantity Calculation')], max_length=25),
        ),
    ]
