# Generated by Django 5.2.7 on 2025-10-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_laminatedfilm_delete_currencyrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaminatedStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LaminatedFilm',
        ),
        migrations.AlterField(
            model_name='salescalculation',
            name='calculation_type',
            field=models.CharField(choices=[('MATERIAL_COST_KG', 'Material Cost per kg'), ('MATERIAL_COST_METER', 'Material Cost per meter'), ('MATERIAL_COST_PIECE', 'Material Cost per piece'), ('ORDER_QUANTITY_KG', 'Order Quantity from kg'), ('ORDER_QUANTITY_METER', 'Order Quantity from meters'), ('ORDER_QUANTITY_PIECE', 'Order Quantity from pieces'), ('ROLL_COST', 'Roll Cost Calculation'), ('LAMINATED_COST', 'Laminated Material Cost')], max_length=25),
        ),
    ]
