# Generated by Django 5.2.7 on 2025-10-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrusionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('PIECES_WEIGHT', 'Pieces to Weight'), ('THICKNESS', 'Thickness Calculation'), ('TAKEUP_SPEED', 'Take-up Speed Adjustment'), ('ROLL_RADIUS', 'Roll Radius/Mass'), ('FILM_LENGTH', 'Film Length from Weight'), ('PRODUCTION_TIME', 'Production Time'), ('BUR_DDR', 'Blown Film Ratios'), ('TENSILE', 'Tensile Strength'), ('ELONGATION', 'Percent Elongation'), ('COF', 'Coefficient of Friction'), ('DART_IMPACT', 'Dart Impact'), ('GAUGE_VARIATION', 'Gauge Variation')], max_length=20)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.plasticmaterial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThicknessMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('thickness_microns', models.FloatField()),
                ('measurement_order', models.IntegerField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thickness_measurements', to='extrusion.extrusioncalculation')),
            ],
            options={
                'ordering': ['measurement_order'],
            },
        ),
    ]
