# Generated by Django 5.2.7 on 2025-10-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_company_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
