# Generated by Django 5.2.7 on 2025-10-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_company_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_id_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secondary_id_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('qc_technician', 'QC Technician'), ('engineer', 'Engineer'), ('other', 'Other')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
