# Generated by Django 5.2.7 on 2025-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_company_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_profile_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_update_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('qc_technician', 'QC Technician'), ('sales representative', 'Sales Representative'), ('engineer', 'Engineer'), ('other', 'Other')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.CharField(choices=[('extrusion', 'Extrusion'), ('printing', 'Printing'), ('lamination', 'Lamination'), ('slitting', 'Slitting'), ('bag_making', 'Bag Making'), ('quality_control', 'Quality Control'), ('maintenance', 'Maintenance'), ('sales', 'Sales'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
